theme = "base16_transparent"

[editor]
soft-wrap.enable = true
end-of-line-diagnostics = "hint"
color-modes = true

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "error"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.auto-save]
focus-lost = true

[keys]
normal.space.H = ":toggle lsp.display-inlay-hints"
