[[language]]
name = "ocaml"
diagnostic-severity = "hint"
formatter = { command = "ocamlformat" }
language-servers = [ "ocamllsp" ]

[language-server.ocamllsp]
command = "ocamllsp"

[language-server.ocamllsp.config]
inlayHints.enable = true
inlayHints.hintPatternVariables = true
inlayHints.hintLetBindings = true
inlayHints.hintFunctionParams = true
codelens.enable = true
extendedHover.enable = true
syntaxDocumentation.enable = true

[[language]]
name = "rust"
auto-format = false
formatter = { command = "cargo fmt", args = ["--", "--config tab_spaces=2"]}
indent = { tab-width = 2, unit = "  " }

[language-server.rust-analyzer.config]
check.command = "clippy"
provideFormatter = true
rustfmt.rangeFormatting.enable = true
cargo.features = "all"

[[language]]
name = "python"
language-servers = [ "basedpyright", "ruff" ]

[language-server.basedpyright.config.python.analysis]
typeCheckingMode = "recommended"

[language-server.basedpyright.config.basedpyright.analysis.inlayHints]
variableTypes = true
callArgumentNames = true
functionReturnTypes = true
genericTypes = true

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]
[language-server.ruff]
command = "ruff"
args = ["server"]
